//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectC_github
{
    using System;
    using System.Collections.Generic;
    
    public partial class cennik
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cennik()
        {
            this.samochody = new HashSet<samochody>();
        }
    
        public int id_cennik { get; set; }
        public string kategoria { get; set; }
        public decimal cena_za_dobe { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<samochody> samochody { get; set; }
    }
}
