//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectC_github
{
    using System;
    using System.Collections.Generic;
    
    public partial class wynajem
    {
        public int id_wynajmu { get; set; }
        public Nullable<int> id_pracownika { get; set; }
        public Nullable<int> id_klienta { get; set; }
        public string nr_rejestracyjny { get; set; }
        public Nullable<System.DateTime> data_od { get; set; }
        public Nullable<System.DateTime> data_do { get; set; }
    
        public virtual klienci klienci { get; set; }
        public virtual pracownicy pracownicy { get; set; }
        public virtual rej_samochody rej_samochody { get; set; }
    }
}
